'use strict';
const fs=require('fs'),path=require('path'),sharp=require('sharp');
const {ssim:computeSSIM}=require('ssim.js');
global.window={};global.katex=require('katex');require('./asy-interp.js');
const R=__dirname,SRC=path.join(R,'comparison','asy_src'),TEX=path.join(R,'comparison','texer_pngs');
const KF=path.join(R,'node_modules','katex','dist','fonts');const RDPI=144,SIGMA=0.15,MAXD=400;
function fontCSS(){const F=[['KaTeX_Main','normal','normal','KaTeX_Main-Regular.woff2'],['KaTeX_Main','italic','normal','KaTeX_Main-Italic.woff2'],['KaTeX_Main','normal','bold','KaTeX_Main-Bold.woff2'],['KaTeX_Main','italic','bold','KaTeX_Main-BoldItalic.woff2'],['KaTeX_Math','normal','normal','KaTeX_Math-Italic.woff2'],['KaTeX_Math','italic','normal','KaTeX_Math-Italic.woff2'],['KaTeX_Math','normal','bold','KaTeX_Math-BoldItalic.woff2'],['KaTeX_Math','italic','bold','KaTeX_Math-BoldItalic.woff2']];let c='';for(const[f,s,w,fl]of F){const p=path.join(KF,fl);if(!fs.existsSync(p))continue;c+=`@font-face{font-family:"${f}";font-style:${s};font-weight:${w};src:url("data:font/woff2;base64,${fs.readFileSync(p).toString('base64')}") format("woff2");}`;}return c;}
function expandVB(s){if(s.indexOf('clip-path="url(#user-clip)"')!==-1)return s;const m=s.match(/viewBox="([^"]+)"/);if(!m)return s;let[vx,vy,vw,vh]=m[1].split(/\s+/).map(Number);let mnx=vx,mny=vy,mxx=vx+vw,mxy=vy+vh;const hc=/<clipPath\s/.test(s);const fo=/<foreignObject\s[^>]*?\bx="([^"]+)"[^>]*?\by="([^"]+)"[^>]*?\bwidth="([^"]+)"[^>]*?\bheight="([^"]+)"[^>]*>/g;let f;while((f=fo.exec(s))){const x=+f[1],y=+f[2],w=+f[3],h=+f[4];if(hc&&(x+w<vx||x>vx+vw||y+h<vy||y>vy+vh))continue;if(x<mnx)mnx=x;if(y<mny)mny=y;if(x+w>mxx)mxx=x+w;if(y+h>mxy)mxy=y+h;}const nx=Math.min(vx,mnx),ny=Math.min(vy,mny),nw=Math.max(vx+vw,mxx)-nx,nh=Math.max(vy+vh,mxy)-ny;if(nx===vx&&ny===vy&&nw===vw&&nh===vh)return s;const ft=n=>+n.toFixed(4);let r=s.replace(m[0],`viewBox="${ft(nx)} ${ft(ny)} ${ft(nw)} ${ft(nh)}"`);const wm=r.match(/\bwidth="([^"]+)"/),hm=r.match(/\bheight="([^"]+)"/);if(wm&&hm){r=r.replace(wm[0],`width="${ft(+wm[1]*(nw/vw))}"`).replace(hm[0],`height="${ft(+hm[1]*(nh/vh))}"`);}return r;}
function embed(s,c){return s.includes('<style>')?s.replace('<style>','<style>'+c):s.replace(/(^<svg[^>]*>)/,'$1<style>'+c+'</style>');}
function toRgba(b,w,h){const o=new Uint8ClampedArray(w*h*4);for(let i=0;i<w*h;i++){o[i*4]=b[i*3];o[i*4+1]=b[i*3+1];o[i*4+2]=b[i*3+2];o[i*4+3]=255;}return o;}
const FC=fontCSS();
async function renderPng(id){const src=fs.readFileSync(path.join(SRC,id+'.asy'),'utf8');const r=global.window.AsyInterp.render('[asy]\n'+src+'\n[/asy]',{containerW:800,containerH:600,labelOutput:'svg-native'});let svg=r.svg;const iw=svg.match(/data-intrinsic-w="([^"]+)"/),ih=svg.match(/data-intrinsic-h="([^"]+)"/);if(iw&&ih)svg=svg.replace(/(<svg[^>]*)\bwidth="[^"]*"/,`$1width="${iw[1]}"`).replace(/(<svg[^>]*)\bheight="[^"]*"/,`$1height="${ih[1]}"`);svg=embed(expandVB(svg),FC);return await sharp(Buffer.from(svg,'utf8'),{density:RDPI}).flatten({background:{r:255,g:255,b:255}}).png().toBuffer();}
async function score(id){const htx=await renderPng(id);const rp=path.join(TEX,id+'.png');if(!fs.existsSync(rp))return null;const rm=await sharp(rp).metadata(),hm=await sharp(htx).metadata();const aw=rm.width||1,ah=rm.height||1,hw=hm.width||1,hh=hm.height||1;let sz;if(aw<100&&ah<100)sz=1;else{const mr=Math.max(hw,hh)/Math.max(aw,ah);sz=Math.exp(-((mr-1)**2)/(2*SIGMA*SIGMA));}const tr=await sharp(rp).flatten({background:{r:255,g:255,b:255}}).trim({threshold:20}).toBuffer({resolveWithObject:true});const th=await sharp(htx).flatten({background:{r:255,g:255,b:255}}).trim({threshold:20}).toBuffer({resolveWithObject:true});const mw=Math.max(tr.info.width,th.info.width),mh=Math.max(tr.info.height,th.info.height);const sc=Math.min(MAXD/mw,MAXD/mh,1);const tw=Math.max(Math.round(mw*sc),11),tht=Math.max(Math.round(mh*sc),11);const rb=await sharp(tr.data).resize(tw,tht,{fit:'fill'}).removeAlpha().raw().toBuffer({resolveWithObject:true});let hb=await sharp(th.data).resize(tw,tht,{fit:'fill'}).removeAlpha().raw().toBuffer({resolveWithObject:true});const w=rb.info.width,h=rb.info.height;if(hb.info.width!==w||hb.info.height!==h)hb=await sharp(hb.data,{raw:{width:hb.info.width,height:hb.info.height,channels:3}}).resize(w,h,{fit:'fill'}).raw().toBuffer({resolveWithObject:true});const{mssim}=computeSSIM({data:toRgba(rb.data,w,h),width:w,height:h},{data:toRgba(hb.data,w,h),width:w,height:h});return{ssim:mssim,sizeScore:sz,combined:mssim*sz};}
(async()=>{
  const mode=process.argv[3];
  if(mode==='--dump'){const out={};for(const id of fs.readFileSync(process.argv[2],'utf8').trim().split(/\s+/).filter(Boolean)){try{const s=await score(id);if(s)out[id]=s;}catch(e){out[id]={err:e.message};}}fs.writeFileSync(process.argv[4],JSON.stringify(out));console.log('dumped',Object.keys(out).length);return;}
  if(mode==='--cmp'){const b=JSON.parse(fs.readFileSync(process.argv[4],'utf8')),a=JSON.parse(fs.readFileSync(process.argv[5],'utf8'));const rows=[];for(const id in a){if(!b[id]||a[id].err||b[id].err)continue;rows.push({id,oC:b[id].combined,nC:a[id].combined,dC:a[id].combined-b[id].combined});}rows.sort((x,y)=>x.dC-y.dC);console.log('id      oldComb newComb  dComb');for(const r of rows){const f=n=>n.toFixed(4);const fl=r.dC<-0.02?' <==REGRESS':(r.dC>0.02?' ++imp':'');console.log(`${r.id}  ${f(r.oC)} ${f(r.nC)} ${(r.dC>=0?'+':'')}${r.dC.toFixed(4)}${fl}`);}const reg=rows.filter(r=>r.dC<-0.02),imp=rows.filter(r=>r.dC>0.02);console.log(`\nSUMMARY ${rows.length}: ${imp.length} improved, ${reg.length} regressed(<-0.02)  meanDC=${(rows.reduce((a,r)=>a+r.dC,0)/(rows.length||1)).toFixed(5)} medianDC=${rows.length?rows[Math.floor(rows.length/2)].dC.toFixed(5):'n/a'}`);return;}
})();
