// comparisons, boolean ops, ternary, increments, compound assignment
write(1 < 2);
write(2 <= 2);
write(3 > 4);
write(3 >= 4);
write(1 == 1.0);
write(1 != 2);
write(true && false);
write(true || false);
write(!true);
write(true ^ true);
write(true ^ false);
write(1 < 2 && 2 < 3);
write(1 < 2 || 1/0 > 0);
write(false && 1/0 > 0);
write(1 < 2 ? 10 : 20);
write(1 > 2 ? 10 : 20);
write(1 > 2 ? 1.5 : 2);
write((1,2) == (1,2));
write((1,2) != (1,3));
write("abc" == "abc");
write("abc" < "abd");
write("B" < "a");
int i = 5;
i += 3;
write(i);
i -= 1;
write(i);
i *= 2;
write(i);
i #= 3;
write(i);
i %= 3;
write(i);
real r = 5;
r /= 2;
write(r);
r ^= 2;
write(r);
int k = 0;
//ASYERR k++; write(k);
write(k);
write(++k);
//ASYERR k--; write(k);
write(--k);
write(k);
int a = 1, b = 2;
a = b = 7;
write(a, b);
write(0.1 + 0.2 == 0.3);
write(abs(0.1 + 0.2 - 0.3) < 1e-9);
bool t = 3 > 2;
write(t);
write(!(t && false));
write(true == false);
write(1 == 1 && 2 == 2 ? "yes" : "no");
write(-1 < 0);
//ASYERR write(max(true, false));
