// library builtins: format()/string() corner cases, array/pen/transform
// helpers, cse5/olympiad/geometry accessors
void wi(int[] a) { write("n=" + string(a.length)); for (int i = 0; i < a.length; ++i) { write(a[i]); } }
void wr(real[] a) { write("n=" + string(a.length)); for (int i = 0; i < a.length; ++i) { write(a[i]); } }
void ws(string[] a) { write("n=" + string(a.length)); for (int i = 0; i < a.length; ++i) { write(a[i]); } }
void wp(pair[] a) { write("n=" + string(a.length)); for (int i = 0; i < a.length; ++i) { write(a[i]); } }
write(format("%+.2f", 3.14159));
write(format("[%-6.1f]", 2.25));
write(format("%#.3g", 2.0));
write(format("%.3g", 1234567.0));
write(format("$%.2e$", 12345.678));
write(format("$%.2e$", 0.00012));
write(format("%.1f", -0.04));
write(format("% .2f", 1.5));
write(format("%10.4f|", pi));
write(format("%.2f", 0.125));
write(format("%.2f", 0.375));
write(format("%.0f", 3.5));
write(format("%5d|", 42));
write(format("%X", 3054));
write(format("%o", 8));
write(format("%g", 100000.0));
write(format("%g", 1000000.0));
write(format("%G", 0.000012345));
write(format("100%%: %.1f", 0.5));
write(format(0.1 + 0.2));
write(format(12345.678));
write(format(-0.00001234));
write(format(2.5e10));
write(string(0.1 + 0.2));
write(string(1/7, 4));
write(string(123456.789, 3));
write(string(-2.5e-7));
write(string(1e15));
write(string(99999.99999, 6));
write((string)(2/3));
write(find("banana", "an", 2));
write(find("banana", "an", 4));
write(rfind("banana", "an"));
write(rfind("banana", "an", 2));
write(replace("aaa", "a", "bb"));
write(replace("abcabc", "bc", ""));
write(reverse("hello world"));
write(insert("hello", 5, "!"));
write(erase("hello", 2, 10));
write(downcase("MiXeD 12"));
write(upcase("MiXeD 12"));
write(stripsuffix("a.b.c", ".c"));
write(stripsuffix("abc", "x"));
int[] a = {5, 1, 4};
a.insert(0, 9, 8);
wi(a);
a.append(new int[]{7});
wi(a);
a.delete(1, 3);
wi(a);
wr(sort(new real[]{3.5, -1, 2}, new bool(real x, real y) {return x > y;}));
ws(sort(new string[]{"pear", "Apple", "apple", "Pear"}));
write(search(new real[]{0.5, 1.5, 2.5}, 1.5));
write(search(new real[]{0.5, 1.5, 2.5}, 9));
write(search(new real[]{0.5, 1.5, 2.5}, 0.1));
wi(findall(new int[]{3, 0, 5, 0} == 0));
write(all(new bool[]{}));
wi(concat(new int[]{1}, new int[]{}, new int[]{2, 3}));
write(determinant(new real[][]{{2, 0, 1}, {1, 3, 2}, {1, 1, 1}}));
wr(solve(new real[][]{{1, 1, 1}, {0, 2, 5}, {2, 5, -1}}, new real[]{6, -4, 27}));
wr(uniform(-1, 1, 4));
wr(abs(new real[]{-2.5, 0, 3}));
wr(min(new real[]{1, 5, 2}, new real[]{4, 0, 3}));
wp(-new pair[]{(1, 2), (-3, 0)});
wp(new pair[]{(1, 2), (3, 4)} - (1, 1));
wp((0, 1) * new pair[]{(1, 0), (0, 1)});
wp(new pair[]{(2, 4)} / 2);
write(dot(new real[]{1, 0.5}, new real[]{2, 4}));
write(abs2((1, 2)));
write(minbound((1, 5), (3, -2)));
write(maxbound(new pair[]{(1, 5), (3, -2), (0, 0)}));
write(cross((1, 2), (3, 4)));
write(exp((1, pi/2)));
write(log((0, 1)));
write(hypot(5, 12));
write(Degrees(pi/4));
write(Degrees(-pi));
write(identity(4.5));
write(Floor(2.5));
write(Ceil(-2.5));
write(Round(2.5));
write(Round(-2.5));
write(erf(0.5));
write(erf(-2));
write(erf(4));
write(Jn(1, 2.5));
write(Yn(1, 2.5));
write(Jn(2, 0.3));
transform T = shift(2, 3)*rotate(30)*scale(2);
write(inverse(T)*(T*(5, -1)));
write(shiftless(T)*(1, 0));
write(T.x);
write(T.yy);
write(T == T);
write(T != shift(1, 1));
write(inverse(shift(4, 5)));
write(colorspace(red + green));
write(colorspace(gray(0.2) + gray(0.3)));
write(colorspace(0.5*orange));
write(colorspace(cmyk(0.1, 0.2, 0.3, 0.4)));
wr(colors(cmyk(0.1, 0.2, 0.3, 0.4)));
wr(colors(cmyk(orange)));
wr(colors(interp(black, white, 0.3)));
wr(colors(interp(gray(0.2), red, 0.5)));
wr(colors(gray(orange)));
write(linewidth(red + linewidth(1.5pt)));
write(linewidth(1pt + blue));
write(fontsize(fontsize(8pt)));
write(fontsize(red + fontsize(20)));
write(opacity(red + opacity(0.3)));
write(linecap(roundcap));
write(linecap(extendcap));
write(linejoin(beveljoin));
write(linejoin(miterjoin));
wr(linetype(longdashdotted));
write(12pt);
write(2cm/pt);
write(labelmargin(fontsize(10pt)) > 0);
write(arrowangle);
write(legendmargin);
write(realMin);
import olympiad;
write(collinear((1, 1), (2, 2), (5, 5.00000000001)));
write(collinear((0, 0), (1, 0), (0, 1)));
write(cyclic((0, 0)--(1, 0)--cycle));
write(cyclic((0, 0)--(1, 0)));
write(concurrent((0, 0), (1, 0), (0, 1), (1, 1), (5, 5), (6, 7)));
import cse5;
pair P = (0,0), Q = (3,4);
write(d(P, Q));
write(WP(P--Q--(3,0), 0.75));
write(point(L(1, P, Q, 1, 2), 1));
write(point(L(2, P, Q), 0));
write(point(CP(P, Q), 0));
