// graph module value-returning helpers
import graph;
real f(real x) { return x^2; }
path g = graph(f, 0, 2);
write(length(g));
write(point(g, 0));
write(point(g, length(g)));
write(point(g, length(g)/2));
write(arclength(g));
path g2 = graph(f, -1, 1, n=4);
write(length(g2));
write(point(g2, 1));
write(point(g2, 1.5));
path g3 = graph(f, 0, 1, operator ..);
write(length(g3));
write(point(g3, 50.5));
path g4 = graph(new real(real x) { return sin(x); }, 0, pi, 10);
write(length(g4));
write(point(g4, 5));
write(point(g4, 2.5));
pair par(real t) { return (cos(t), sin(t)); }
path pg = graph(par, 0, pi/2, 4);
write(length(pg));
write(point(pg, 2));
write(point(pg, 2.5));
path pg2 = graph(par, 0, 2pi, 8, operator ..);
write(length(pg2));
write(point(pg2, 1.5));
path c1 = Circle((0,0), 1);
write(length(c1));
write(point(c1, 100));
write(point(c1, 0.5));
path c2 = Circle((1,1), 2, 8);
write(length(c2));
write(point(c2, 1));
write(point(c2, 1.5));
path a1 = Arc((0,0), 1, 0, 90);
write(length(a1));
write(point(a1, length(a1)));
write(point(a1, 200.5));
path a2 = Arc((0,0), 2, 0, 90, 3);
write(length(a2));
write(point(a2, 1));
write(point(a2, 1.5));
real[] xs = {0, 1, 2, 3};
real[] ys = {0, 1, 4, 9};
path gd = graph(xs, ys);
write(length(gd));
write(point(gd, 1.5));
path gp = graph(new pair[]{(0,0), (1,2), (2,1)});
write(length(gp));
write(point(gp, 0.5));
path pol = polargraph(new real(real t) { return 1 + cos(t); }, 0, pi, 4);
write(length(pol));
write(point(pol, 1));
write(point(pol, 2.5));
path gh = graph(f, 0, 2, Hermite);
write(length(gh));
write(point(gh, 50.5));
