// geometry.asy module (point/line/circle/triangle structs) - value-returning helpers
import geometry;
point A = (0,0), B = (4,0), C = (1,3);
triangle t = triangle(A, B, C);
write((pair)circumcenter(t));
write((pair)incenter(t));
write((pair)orthocentercenter(t));
write((pair)centroid(t));
write(circumcircle(t).r);
write(incircle(t).r);
write((pair)circumcircle(t).C);
write((pair)midpoint(segment(A, B)));
line l = line(A, B);
write((pair)(projection(l)*C));
write(distance(C, l));
circle c = circle((point)(0,0), 2);
write(c.r);
write((pair)c.C);
line l2 = line((point)(-3,1), (point)(3,1));
point[] ip = intersectionpoints(l2, c);
write(ip.length);
write((pair)ip[0]);
write((pair)ip[1]);
write((pair)intersectionpoint(line(A, C), line(B, (point)(3,3))));
write(t.a());
write(t.b());
write(t.c());
//ASYERR write(area(t));
write((pair)(reflect(line(A, B))*C));
write((pair)(rotate(90, A)*B));
write(length(segment(A, C)));
write(abs(C - A));
write(degrees(t.alpha()));
write(t.alpha());
write((pair)foot(t.VC));
write((pair)midpoint(t.AB));
write((pair)t.A);
write(abs(circumcenter(A, B, C) - A));
write((pair)circumcenter(A, B, C));
write((pair)incenter(A, B, C));
write((pair)orthocentercenter(A, B, C));
write((pair)centroid(A, B, C));
write(inradius(A, B, C));
//ASYERR write(circumradius(A, B, C));
write((pair)intersectionpoint(line(A, C), line(B, (point)(3, 3))));
