// pair arithmetic and functions
pair z = (3,4), w = (1,-2);
write(z);
write(z + w);
write(z - w);
write(2*z);
write(z*2.5);
write(z/2);
write(z*w);
write(z/w);
write(-z);
write(conj(z));
write(abs(z));
write(length(z));
write(abs2(z));
write(angle(z));
write(degrees(z));
write(degrees((-1,0)));
write(degrees((0,-1)));
write(degrees((-1,-0.0001)));
write(angle((-1,0)));
write(angle((0,-1)));
write(unit(z));
write(unit((0,0)));
write(dot(z, w));
write(cross(z, w));
write(xpart(z));
write(ypart(z));
write(z.x);
write(z.y);
write(dir(30));
write(dir(90));
write(dir(180));
write(dir(-45));
write(dir(360));
write(dir(z));
write(expi(pi/3));
write(expi(pi));
write(rotate(90)*z);
write(rotate(45)*(1,0));
write(rotate(90, (1,1))*(2,1));
write(sqrt((0,1)));
write(sqrt((-4,0)));
write(sqrt(z));
write(z^2);
write(z^-1);
write(z^0);
write(I);
write(I*I);
write(2+3I);
write((1,1)*I);
write(exp((0,pi)));
write(log(z));
write((1,2) == (1.0,2.0));
write(minbound(z, w));
write(maxbound(z, w));
write(midpoint((0,0)--(4,2)));
write(interp(z, w, 0.25));
write((z + w)/2);
write(z * (0.5, 0.5));
pair p = (1/3, 2/3);
write(p);
write((1e-20, 1));
write((0.1+0.2, 1e10));
write(Sin(30)*z);
write(dir(z - w));
write(realmult(z, w));
write(z == (3,4) ? 1 : 0);
pair q;
write(q);
q = z;
q += (1,1);
write(q);
q *= 2;
write(q);
write(xpart(dir(60)) == 0.5);
write(dir(120));
write(dir(210));
write(dir(0.5));
//ASYERR write(bisector((1,0), (0,1)) );
