// string conversion and string functions
write("x" + string(3));
write("x" + string(3.0));
write("x" + string(1/3));
write("x" + string(2.5));
write("x" + string(1e-5));
write("x" + string(123456789.0));
write("x" + string(1e20));
write("x" + string(pi));
write("x" + string(-0.5));
//ASYERR write("x" + string((1,2)));
//ASYERR write("x" + string((0.5,-1/3)));
write(string(pi, 3));
write(string(pi, 10));
write(string(1234.5678, 2));
write(string(0.000123456, 2));
//ASYERR write(string(true));
write(format("%d", 42));
write(format("%5.2f", pi));
write(format("%.3f", 2/3));
write(format("%e", 12345.678));
write(format("%g", 0.0001));
write(format("$%.1f$", 2.25));
write(format("%i", 7));
write(format("%03d", 7));
//ASYERR write(format("%s", "hi"));
write(format("%f", 1.0));
write(format("%.0f", 2.5));
write(format(3.14159));
write(format(1/3));
write(format(10));
write(format(-2.5));
write(format(1e-7));
write(format("%x", 255));
write(length("hello"));
write(length(""));
write(substr("hello", 1, 3));
write(substr("hello", 2));
write(find("hello", "l"));
write(find("hello", "z"));
write(find("hello", "l", 3));
write(rfind("hello", "l"));
write(replace("hello world", "o", "0"));
write(reverse("abc"));
write(insert("abc", 1, "XY"));
write(erase("abcdef", 1, 2));
write(downcase("HeLLo"));
write(upcase("HeLLo"));
write("a" + "b" + "c");
write("n=" + (string)5);
write((string)2.5);
write((real)"2.5" + 1);
write((int)"42" + 1);
string s = "A";
s += "B";
write(s);
//ASYERR write(s + 1);
//ASYERR write(s + 1.5);
write("val: ", 3);
write("val: ", 2.5);
write("pair: ", (1,2));
write(1, 2);
//ASYERR write(1, 2.5, "x");
write("$" + string(sqrt(2), 4) + "$");
write("$" + (string)(1/3) + "$");
write(stripextension("file.asy"));
write(stripdirectory("a/b/c.txt"));
write(stripsuffix("hello.txt", ".txt"));
write(string(12.0));
write(string(1e6));
write(string(1234567.0));
write(string(0.1));
write(string(100000.0*3));
write(string(-1e-10));
write(string(2^31));
write(string(sqrt(3)/2));
write(time("%Y") != "");
